#define  TBEGIN 0
#define  LOOP 1
#define  ELSE 2
#define  END 3
#define  IF 4
#define  READ 5
#define  WRITE 6
#define  THEN 7
#define  VAR 8
#define  WHILE 9
#define  FUNC 10
#define  RETURNS 11

#define  NAME 20
#define  NUMBER 21
#define  PLUS 22
#define  MINUS 23
#define  MULT 24
#define  DIV 25
#define  LBRA 26
#define  RBRA 27
#define  LT 28
#define  LTE 29
#define  EQ 30
#define  NEQ 31
#define  ASSIGN 32
#define  SEMI 33
#define  COMMA 34
